### ISSUE TITLE
Measurements - event_id column possible?

### ISSUE THREAD

**Issue by sneJ-** [datagiraffe/cellservice#10]
Hey,
is it possible to add an event_id column in the Measurements table to map events (call, dataRecords, LocationUpdates...) easily with the measurements?
Right now it is only possible using the time column. But the times in the events differ from the times in the Measurements table. The measurements time from a call is every time between the starttime and endtime of a call, so it's with some effort map able. But the LocationUpdate table for example just has one time column and isn't indirect map able.

**Comment by datagiraffe** [comment]
Originally the measurements where only thought to be used to generate a cell coverage area. Thus making them independent of events.
However, it may be a good idea for verification purposes to know *where* an event has taken place on a more fine grained level.

In terms of the schema - how would you propose to include it?
At the moment the events are all in different tables, so its not really possible to use one event id referencing them.
I could imagine an additional event table that keeps track of all events. Calls, LocationUpdates, TextMessages etc. and Measurements could reference this table?

**Comment by sneJ-** [comment]
Wouldn't it be enough to use the tuple event and event_id as unique identifier?

**Comment by datagiraffe** [comment]
Added event_id and event_type to Measurements table and modified record insertion accordingly. See f781b4ba683ff10b57f77b1b0b4f1b25bce558a3 for details.
